In [2]:
import pandas as pd
import numpy as np

In [17]:
file = 'question_data/Final_project_Tonyquestion.csv'
mental_df = pd.read_csv(file)

In [18]:
mental_df = mental_df.drop(columns="Unnamed: 6")
mental_df.head()

,Self-employed,Tech_employee,Current_disorder,Condition,Gender,Remote
0,No,NaN,No,NaN,Male,Sometimes
1,No,NaN,Yes,"Anxiety Disorder (Generalized, Social, Phobia,...",Male,Never
2,No,NaN,No,NaN,Male,Always
3,Yes,NaN,Yes,"Anxiety Disorder (Generalized, Social, Phobia,...",Male,Sometimes
4,No,Yes,Yes,"Anxiety Disorder (Generalized, Social, Phobia,...",Female,Sometimes

In [20]:
mental_df["Self-employed"] = mental_df["Self-employed"].fillna("No")
mental_df["Tech_employee"] = mental_df["Tech_employee"].fillna("No")

mental_df.head()

,Self-employed,Tech_employee,Current_disorder,Condition,Gender,Remote
0,No,No,No,NaN,Male,Sometimes
1,No,No,Yes,"Anxiety Disorder (Generalized, Social, Phobia,...",Male,Never
2,No,No,No,NaN,Male,Always
3,Yes,No,Yes,"Anxiety Disorder (Generalized, Social, Phobia,...",Male,Sometimes
4,No,Yes,Yes,"Anxiety Disorder (Generalized, Social, Phobia,...",Female,Sometimes

In [43]:
#check to see if any NaN in condition are misplaced
for index, row in mental_df.iterrows():
    if row[2] == "Yes":
        if row[3] == "NaN":
            print(row[3])

In [45]:
mental_df["Condition"] = mental_df["Condition"].fillna("None")

Self-employed  Tech_employee  Current_disorder  Condition                                    Gender  Remote
No             No             No                None                                         Male    Sometimes    157
                              Maybe             None                                         Male    Sometimes     75
                              No                None                                         Male    Never         60
                                                                                                     Always        60
Yes            No             No                None                                         Male    Sometimes     44
                                                                                                                 ...
No             Yes            Maybe             None                                         Other   Never          1
               No             Yes               Traumatic Brain Injury                       Other   Sometimes      1
                                                Substance Use Disorder|Addictive Disorder    Male    Never          1
                                                Stress Response Syndromes|Sleeping Disorder  Male    Never          1
               0              Maybe             None                                         Female  Never          1
Length: 356, dtype: int64

In [52]:
#print(mental_df["Self-employed"].value_counts())
#print(mental_df["Tech_employee"].value_counts())
#print(mental_df["Current_disorder"].value_counts())
#print(mental_df["Condition"].value_counts())
print(mental_df["Gender"].value_counts())
#print(mental_df["Remote"].value_counts())


#set 0 to no for tech_employee
#set maybe to no for current_disorder
#condition is going to be a wreck

Male       1046
Female      327
Other        32
Male         14
FeMale        8
feMale        3
 FeMale       1
Female        1
Name: Gender, dtype: int64

In [50]:
#all "Maybe" have no condition listed
for index, row in mental_df.iterrows():
    if row[2] == "Maybe":
        print(row[3])

None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None